#!/bin/bash
echo "CREATE DATABASE IF NOT EXISTS $DB_NAME;" > $DB_INIT_FILE
echo "CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';" >> $DB_INIT_FILE
echo "GRANT ALL PRIVILEGES ON *.* TO '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD' WITH GRANT OPTION;" >> $DB_INIT_FILE
echo "FLUSH PRIVILEGES;" >> $DB_INIT_FILE
sleep 5
mysql_install_db 
mysqld